### ISSUE TITLE
Custom weighting

### ISSUE THREAD

**Issue by jtseven** [jtseven/Fundless#5]
In GitLab by @lennart.reiher on Aug 7, 2021, 13:37

I would like to have the option of setting a custom weighting. See below for how this could be configured.

**Thoughts**:
- weighting expressed in fractions (0.3 = 30%)
- if sum of fractions exceeds 1, throw error or simply normalize to 1
- if not all symbols have a fraction defined, distribute equally among the missing ones
- ignore fractions of symbols that are not used

```yaml
portfolio:
    mode:
      options:
        - cherry_pick
        - index  # not yet implemented
      selected: cherry_pick
    cherry_pick:
      symbols:  # as defined by coingecko
        - btc
        - eth
    index:
      top_n: 10
      exclude_symbols: [xrp]    # probably a good idea to exclude stable coins
    weighting:
      options:
        - equal
        - custom                # <----------
        - market_cap
        - sqrt_market_cap       # square root of market cap
        - cbrt_market_cap       # cubic root
        - sqrt_sqrt_market_cap  # fourth root
      selected: custom          # <----------
      custom:                   # <----------
        btc: 0.3                # <----------
        eth: 0.7                # <----------
```
